# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "crawford/slackware-14.2"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
	vb.customize ["modifyvm", :id, "--cpus", 3]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
	#echo "Downloading Java Slack Package..."
    #wget --quiet -r -nH -np --cut-dirs=4 -R index.html* http://ftp.slackware.com/pub/slackware/slackware-current/extra/java/
	#echo -n "done."
	#pushd java/
	#echo -n "Downloading Java..."
    #wget --quiet --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-i586.tar.gz
	#echo "done."
    #chmod +x java.SlackBuild 
    #./java.SlackBuild
	#sudo /sbin/installpkg --terse /tmp/jdk*
	#popd
    #rm -rf java/ /tmp/jdk*
	echo "Downloading Java..."
	wget --quiet https://www.dropbox.com/s/3rxx4eunlogcaku/jdk-8u101-i586-1.txz
	echo "Downloading Java...DONE"
	echo "Installing Java..."
	sudo /sbin/installpkg --terse jdk-8u101-i586-1.txz
	echo "Installing Java...DONE"
	rm -rf jdk-8u101-i586-1.txz
	echo "Downloading Elasticsearch..."
	wget --quiet https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.1/elasticsearch-2.4.1.tar.gz
	echo "Downloading Elasticsearch...DONE"
	echo "Extracting Elasticsearch..."
	tar xzf elasticsearch-2.4.1.tar.gz
	echo "Extracting Elasticsearch...DONE"
	echo "Configuring Elasticsearch..."
	chown -R vagrant:users elasticsearch-2.4.1
	rm 	-f elasticsearch-2.4.1.tar.gz
	mkdir opt
	mv elasticsearch-2.4.1 opt
	ln -s opt/elasticsearch-2.4.1/bin/elasticsearch
	echo "Configuring Elasticsearch...DONE"
	rm -f ip_address.txt
  SHELL
end
